spin_manifest_version = 2

[application]
name = "redirect-to-example"
version = "0.1.0"
description = "Always redirect incoming requests to https://example.com"

[[trigger.http]]
route = "/..."
component = "redirect-to-example"

[component.redirect-to-example]
source = "dist/redirect-to-example.wasm"
exclude_files = ["**/node_modules"]
[component.redirect-to-example.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.js"]
